### ISSUE TITLE
Ingredients Display Edit 

### ISSUE THREAD

**Issue by Malachi046** [yycorcino/meal-planner-app#8]
This will give functionality to the edit button from the ingredients display. Feature should include the following 

-Have an edit state. This should be a boolean value that is true when you hit edit
-When you hit edit, the button should change to say "save" 
-hitting save should set edit state to false 

simpler explanation
Hitting Edit -> editState = true
Hitting Save -> editState = false

 If (editState == false) -> button says "Edit"
else -> button says "Save" 

Edit state should also: 

-Allow user to select the name and write a new one
-Add delete button to remove ingredient entirely
-Saving should commit changes 

Ingredients page's "Add new ingredient button" was previously a placeholder and should now open a blank ingredient display in the edit state so they can write in the info. Saving should add it as a new ingredient to the list

**Comment by jaredkeeler2** [comment]
This has been completed
